<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<style>
    .contenu-card{
        position:relative;
    }
    .black-hover{
        display: none;
        height: 100%;
        width: 100%;
        background: rgba(52, 58, 64, 0.8);
        z-index: 25;
        position: absolute;
        top: 0;
    }
     .contenu-card:hover .black-hover{
      display:flex;   
     }
     .trashBtn{
         margin:auto;
         color:white;
     }
    </style>


    <div class="container" style="margin-top:20px" >
        <div class="row">
            <div class="col-lg-5 mx-auto text-center">
            <nav class="navbar navbar-light bg-light">
  <form class="form-inline">
    <input class="form-control mr-sm-2"  id="search" type="search" placeholder="Rechercher" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Rechercher</button>
     <div id="results"></div>
  </form>
</nav>
            </div> 
        </div>
  <div class="row" >
     
     

            <?php foreach ($admins as $admin) : ?>
      
        <div class="col-lg-5 mx-auto text-center">
           
                  <div class="card photo " style="width: 18rem; margin-top: 25px; margin: 0px 30px 70px;">
                     <!-- <span class="glyphicon glyphicon-euro"></span>-->
                      <div class='contenu-card'style="cursor:pointer" >
                          <img class="card-img-top" id="id"  value="<?=$admin->id?>"src="/img/upload/<?=$admin->id?>"alt="Card image cap">
                      <div class='black-hover'> <i class="trashBtn fas fa-trash"></i></div>
                      </div>
                                <div class="card-body">
                     <p class="card-text"><?=$admin->titre?></p>
           
                                </div>
 <a href="/admin/edit/<?=$admin->id?>" class="btn btn-info" role="button">Editer</a>                      
                    </div>
            </div>
          
            <?php endforeach; ?>
       
    </div>
</div>