 
<style>
    
    .photo{
-webkit-box-shadow: 1px 2px 25px 0px rgba(0,0,0,0.39);
-moz-box-shadow: 1px 2px 25px 0px rgba(0,0,0,0.39);
box-shadow: 1px 2px 25px 0px rgba(0,0,0,0.39);

overflow: hidden;
border-radius: 5px;
    
    margin: 0px 20px 20px;
    float:left;
}

.zoom {
width: 320px;
height: 240px;
}
.image {
width: 100%;
height: 100%;
}
.image img {
/* La transition s'applique à la fois sur la largeur et la hauteur, avec une durée d'une seconde. */
-webkit-transition: all 1s ease; /* Safari et Chrome */
-moz-transition: all 1s ease; /* Firefox */
-ms-transition: all 1s ease; /* Internet Explorer 9 */
-o-transition: all 1s ease; /* Opera */
transition: all 1s ease;
}
.image:hover img {
/* L'image est grossie de 25% */
-webkit-transform:scale(1.25); /* Safari et Chrome */
-moz-transform:scale(1.25); /* Firefox */
-ms-transform:scale(1.25); /* Internet Explorer 9 */
-o-transform:scale(1.25); /* Opera */
transform:scale(1.25);
}    
    
</style>

<header class="masthead text-center text-white d-flex">
       <div class="container global">
        <div class="container my-auto">
        <div class="row">
          <div class="col-lg-10 mx-auto">
            <h1 class="text-uppercase">
              <strong>Portfolio</strong>
            </h1>
            <hr>
          </div>
          <div class="col-lg-8 mx-auto">
            <p class="text-faded mb-5">Portfolio Alan</p>
            
          </div>
        </div>
      </div>

 </div>
  
  
   
</header>
  <section class="bg-primary" id="about">
      
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto text-center">
            <h2 class="section-heading text-white">La photo</h2>
            <hr class="light my-4">
            <p class="text-faded mb-4">Photo de voyages</p>
          
    
            <?php foreach ($admins as $admin) : ?>
            <?php  if($admin->affichage == 1){ ?>
                  <div class="card photo " style="width: 18rem; margin-top: 20px; margin: 0px 30px 70px;">
                     
                      <img class="card-img-top" src="/img/upload/<?=$admin->id?>"alt="Card image cap">
                        
     <div class="card-body">
    <p class="card-text"><?=$admin->titre?></p>
           
  </div>
</div>
 <?php  } ?>           
         
            <?php endforeach; ?>
          
             
            
          </div>
        </div>
      </div>
</section>


<section id="services">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h2 class="section-heading">Skills</h2>
            <hr class="my-4">
          </div>
        </div>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-md-6 text-center">
            <div class="service-box mt-5 mx-auto">
              <i class="fa fa-4x fa-diamond text-primary mb-3 sr-icons"></i>
              <h3 class="mb-3">Javascript</h3>
              <div id="js-circle"></div>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 text-center">
            <div class="service-box mt-5 mx-auto">
              <i class="fa fa-4x fa-paper-plane text-primary mb-3 sr-icons"></i>
              <h3 class="mb-3">PHP</h3>
             <div id="php-circle"></div>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 text-center">
            <div class="service-box mt-5 mx-auto">
              <i class="fa fa-4x fa-newspaper-o text-primary mb-3 sr-icons"></i>
              <h3 class="mb-3">SQL</h3>
              
             <div id="test-circle"></div>
               
            </div>
          </div>
          <div class="col-lg-3 col-md-6 text-center">
            <div class="service-box mt-5 mx-auto">
              <i class="fa fa-4x fa-heart text-primary mb-3 sr-icons"></i>
              <h3 class="mb-3">Html</h3>
               <div id="html-circle"></div>
            </div>
          </div>
        </div>
      </div>
</section>


<script>
    $( document ).ready(function() {
	$("#test-circle").circliful({
                animationStep: 5,
                foregroundBorderWidth: 5,
                backgroundBorderWidth: 15,
                percent: 75
           });
           
           $("#php-circle").circliful({
                animationStep: 5,
                foregroundBorderWidth: 5,
                backgroundBorderWidth: 15,
                percent: 75
           });
           
            $("#js-circle").circliful({
                animationStep: 5,
                foregroundBorderWidth: 5,
                backgroundBorderWidth: 15,
                percent: 75
           });
           
           $("#html-circle").circliful({
                animationStep: 5,
                foregroundBorderWidth: 5,
                backgroundBorderWidth: 15,
                percent: 75
           });
   });
</script>

<script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>